// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuwkuomczaoxbaysabii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1d2t1b21jemFveGJheXNhYmlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTQyOTIsImV4cCI6MjA3MzU5MDI5Mn0.a4HUJTdmrgrbAa_F6-JWCvvaJ_zs71qEon_2aY0434c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});